---

- name: Ensure that the /tmp/ruby directory exists
  file: state=directory path=/tmp/ruby

- name: Download the Ruby source
  get_url: url={{ url }} dest=/tmp/ruby

- name: Extract the Ruby source
  shell: /bin/tar -xf ruby-2.1.0.tar.gz chdir=/tmp/ruby creates={{ path }}

- name: Configure the Ruby source
  shell: ./configure chdir={{ path }} creates={{ path }}/Makefile

- name: Compile the Ruby source
  shell: /usr/bin/make chdir={{ path }} creates={{ path }}/ruby

- name: Install Ruby
  sudo: True
  shell: /usr/bin/make install chdir={{ path }} creates=/usr/local/bin/ruby

- name: Install Bundler
  sudo: True
  shell: /usr/local/bin/gem install bundler creates=/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.5.3

- name: Install the charlock_holmes gem
  sudo: True
  shell: /usr/local/bin/gem install charlock_holmes --version '0.6.9.4'
